package com.globemed.staff;

/**
 * Represents a staff member in the GlobeMed system.
 */
public class Staff {
    private int staffId; // Auto-generated by DB for existing staff
    private String username;
    private String passwordHash; // Store as hash, not plain text in a real app. For this assignment, it's just the input password.
    private String role; // e.g., "Doctor", "Nurse", "Admin"

    // Constructor for creating new staff (ID is auto-generated)
    public Staff(String username, String passwordHash, String role) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.role = role;
    }

    // Constructor for existing staff (ID is known)
    public Staff(int staffId, String username, String passwordHash, String role) {
        this.staffId = staffId;
        this.username = username;
        this.passwordHash = passwordHash;
        this.role = role;
    }

    // Getters
    public int getStaffId() { return staffId; }
    public String getUsername() { return username; }
    public String getPasswordHash() { return passwordHash; } // Renamed to reflect storage
    public String getRole() { return role; }

    // Setters (for updating existing staff details)
    public void setStaffId(int staffId) { this.staffId = staffId; }
    public void setUsername(String username) { this.username = username; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public void setRole(String role) { this.role = role; }

    @Override
    public String toString() {
        return String.format("ID: %d | Username: %s | Role: %s", staffId, username, role);
    }
}