package com.globemed.utils;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class TextReportPrinter {

    private static final Font FONT_TITLE = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
    private static final Font FONT_HEADER_BOLD = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
    private static final Font FONT_NORMAL = new Font(Font.FontFamily.COURIER, 10, Font.NORMAL); // Courier for monospace text
    private static final Font FONT_FOOTER = new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC);

    /**
     * Generates a PDF from a given text report.
     * @param reportTitle The title for the report in the PDF.
     * @param reportContent The actual text content of the report.
     * @param patientId The patient ID associated with the report (for filename).
     * @return The filename of the generated PDF, or null if an error occurred.
     */
    public static String printTextReport(String reportTitle, String reportContent, String patientId) {
        String filename = String.format("%s-%s-%s.pdf", reportTitle.replace(" ", ""), patientId, LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")));
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(filename));
            document.open();

            // --- Header ---
            Paragraph title = new Paragraph("GlobeMed Healthcare - " + reportTitle, FONT_TITLE);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            // Report Details
            document.add(new Paragraph("Generated For Patient ID: " + patientId, FONT_HEADER_BOLD));
            document.add(new Paragraph("Generation Date: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), FONT_HEADER_BOLD));
            document.add(Chunk.NEWLINE);

            // --- Report Content ---
            // Use FONT_NORMAL (Courier) for the main content to preserve spacing
            Paragraph content = new Paragraph(reportContent, FONT_NORMAL);
            document.add(content);
            document.add(Chunk.NEWLINE);

            // --- Footer ---
            document.add(new Paragraph("Generated by GlobeMed Healthcare System", FONT_FOOTER));

            System.out.println("PDF Text Report generated: " + filename);
            return filename;

        } catch (DocumentException | IOException e) {
            System.err.println("Error generating PDF text report: " + e.getMessage());
            e.printStackTrace();
            return null;
        } finally {
            if (document.isOpen()) {
                document.close();
            }
        }
    }
}