name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: java
          package-name: healthcare-system

  build-artifacts:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: healthcare-system-jar
          path: target/healthcare-system-${{ needs.release-please.outputs.version }}.jar

  build-windows:
    runs-on: windows-latest
    needs: build-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: healthcare-system-jar
          path: .

      - name: Package Windows app
        run: |
          jpackage --type exe \
            --input . \
            --main-jar healthcare-system-${{ needs.release-please.outputs.version }}.jar \
            --main-class com.globemed.healthcare.Main \
            --name "Healthcare System" \
            --app-version ${{ needs.release-please.outputs.version }} \
            --vendor "YourCompany" \
            --win-menu --win-shortcut

      - uses: actions/upload-artifact@v4
        with:
          name: healthcare-system-windows
          path: "*.exe"

  build-macos:
    runs-on: macos-latest
    needs: build-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: healthcare-system-jar
          path: .

      - name: Package macOS app
        run: |
          jpackage --type dmg \
            --input . \
            --main-jar healthcare-system-${{ needs.release-please.outputs.version }}.jar \
            --main-class com.globemed.healthcare.Main \
            --name "Healthcare System" \
            --app-version ${{ needs.release-please.outputs.version }} \
            --vendor "YourCompany" \
            --icon src/main/resources/icon.icns

      - uses: actions/upload-artifact@v4
        with:
          name: healthcare-system-macos
          path: "*.dmg"

  build-linux:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: healthcare-system-jar
          path: .

      - name: Package Linux app
        run: |
          jpackage --type deb \
            --input . \
            --main-jar healthcare-system-${{ needs.release-please.outputs.version }}.jar \
            --main-class com.globemed.healthcare.Main \
            --name "Healthcare System" \
            --app-version ${{ needs.release-please.outputs.version }} \
            --vendor "YourCompany"
          jpackage --type rpm \
            --input . \
            --main-jar healthcare-system-${{ needs.release-please.outputs.version }}.jar \
            --main-class com.globemed.healthcare.Main \
            --name "Healthcare System" \
            --app-version ${{ needs.release-please.outputs.version }} \
            --vendor "YourCompany"

      - uses: actions/upload-artifact@v4
        with:
          name: healthcare-system-linux
          path: "*.deb"

      - uses: actions/upload-artifact@v4
        with:
          name: healthcare-system-linux-rpm
          path: "*.rpm"

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [release-please, build-windows, build-macos, build-linux]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.release-please.outputs.version }}
          files: |
            ./artifacts/**/*.jar
            ./artifacts/**/*.exe
            ./artifacts/**/*.dmg
            ./artifacts/**/*.deb
            ./artifacts/**/*.rpm